### ISSUE TITLE
Release 1.1.0: Annotation POST jobs/search fails - leads to empty 'documents' page on UI

### ISSUE THREAD

**Issue by spiridonovfed** [epam/badgerdoc#101]
INFO:     10.233.90.227:38012 - "POST /api/v1/jobs/jobs/search HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/uvicorn/protocols/http/h11_impl.py", line 373, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/usr/local/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.8/site-packages/fastapi/applications.py", line 208, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.8/site-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.8/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc from None
  File "/usr/local/lib/python3.8/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.8/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc from None
  File "/usr/local/lib/python3.8/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 580, in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 241, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 52, in app
    response = await func(request)
  File "/usr/local/lib/python3.8/site-packages/fastapi/routing.py", line 216, in app
    solved_result = await solve_dependencies(
  File "/usr/local/lib/python3.8/site-packages/fastapi/dependencies/utils.py", line 550, in solve_dependencies
    solved = await call(**sub_values)
  File "/usr/local/lib/python3.8/site-packages/tenant_dependency-0.1.3-py3.8.egg/tenant_dependency/dependency.py", line 52, in __call__
    decoded = self.decode_rs256(token)
  File "/usr/local/lib/python3.8/site-packages/tenant_dependency-0.1.3-py3.8.egg/tenant_dependency/dependency.py", line 99, in decode_rs256
    signing_key = self.jwk_client.get_signing_key_from_jwt(token)
  File "/usr/local/lib/python3.8/site-packages/PyJWT-2.3.0-py3.8.egg/jwt/jwks_client.py", line 59, in get_signing_key_from_jwt
    return self.get_signing_key(header.get("kid"))
  File "/usr/local/lib/python3.8/site-packages/PyJWT-2.3.0-py3.8.egg/jwt/jwks_client.py", line 41, in get_signing_key
    signing_keys = self.get_signing_keys()
  File "/usr/local/lib/python3.8/site-packages/PyJWT-2.3.0-py3.8.egg/jwt/jwks_client.py", line 28, in get_signing_keys
    jwk_set = self.get_jwk_set()
  File "/usr/local/lib/python3.8/site-packages/PyJWT-2.3.0-py3.8.egg/jwt/jwks_client.py", line 24, in get_jwk_set
    data = self.fetch_data()
  File "/usr/local/lib/python3.8/site-packages/PyJWT-2.3.0-py3.8.egg/jwt/jwks_client.py", line 20, in fetch_data
    with urllib.request.urlopen(self.uri) as response:
  File "/usr/local/lib/python3.8/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/lib/python3.8/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/local/lib/python3.8/urllib/request.py", line 640, in http_response
    response = self.parent.error(
  File "/usr/local/lib/python3.8/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/local/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/usr/local/lib/python3.8/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 503: Service Unavailable
19-Dec-22 12:23:55 - [ERROR] - uvicorn.error - (h11_impl.py).run_asgi(376) - Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/uvicorn/protocols/http/h11_impl.py", line 373, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/usr/local/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.8/site-packages/fastapi/applications.py", line 208, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.8/site-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.8/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc from None
  File "/usr/local/lib/python3.8/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.8/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc from None
  File "/usr/local/lib/python3.8/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 580, in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 241, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 52, in app
    response = await func(request)
  File "/usr/local/lib/python3.8/site-packages/fastapi/routing.py", line 216, in app
    solved_result = await solve_dependencies(
  File "/usr/local/lib/python3.8/site-packages/fastapi/dependencies/utils.py", line 550, in solve_dependencies
    solved = await call(**sub_values)
  File "/usr/local/lib/python3.8/site-packages/tenant_dependency-0.1.3-py3.8.egg/tenant_dependency/dependency.py", line 52, in __call__
    decoded = self.decode_rs256(token)
  File "/usr/local/lib/python3.8/site-packages/tenant_dependency-0.1.3-py3.8.egg/tenant_dependency/dependency.py", line 99, in decode_rs256
    signing_key = self.jwk_client.get_signing_key_from_jwt(token)
  File "/usr/local/lib/python3.8/site-packages/PyJWT-2.3.0-py3.8.egg/jwt/jwks_client.py", line 59, in get_signing_key_from_jwt
    return self.get_signing_key(header.get("kid"))
  File "/usr/local/lib/python3.8/site-packages/PyJWT-2.3.0-py3.8.egg/jwt/jwks_client.py", line 41, in get_signing_key
    signing_keys = self.get_signing_keys()
  File "/usr/local/lib/python3.8/site-packages/PyJWT-2.3.0-py3.8.egg/jwt/jwks_client.py", line 28, in get_signing_keys
    jwk_set = self.get_jwk_set()
  File "/usr/local/lib/python3.8/site-packages/PyJWT-2.3.0-py3.8.egg/jwt/jwks_client.py", line 24, in get_jwk_set
    data = self.fetch_data()
  File "/usr/local/lib/python3.8/site-packages/PyJWT-2.3.0-py3.8.egg/jwt/jwks_client.py", line 20, in fetch_data
    with urllib.request.urlopen(self.uri) as response:
  File "/usr/local/lib/python3.8/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/lib/python3.8/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/local/lib/python3.8/urllib/request.py", line 640, in http_response
    response = self.parent.error(
  File "/usr/local/lib/python3.8/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/local/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/usr/local/lib/python3.8/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 503: Service Unavailable

**Comment by spiridonovfed** [comment]
'documents' webpage is empty:
![image](https://user-images.githubusercontent.com/76848937/208436287-1a5062b4-1447-47cf-bcb7-cf1db85aa54c.png)

But it show documents, if we choose the button - show as list:
![image](https://user-images.githubusercontent.com/76848937/208436544-ad7fe293-d854-45fe-b3cf-1d8463bf70c2.png)

**Comment by spiridonovfed** [comment]
'Annotation' microservice is down due to alembic migrations conflicts

**Comment by spiridonovfed** [comment]
Logs of annotation microservice:

C:\Users\Fedor_Spiridonov>kubectl -n dev2 logs annotation-7f5b9cc574-lflvk
INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
INFO  [alembic.runtime.migration] Will assume transactional DDL.
ERROR [alembic.util.messaging] Can't locate revision identified by 'b13e7ea70983'
FAILED: Can't locate revision identified by 'b13e7ea70983'

**Comment by spiridonovfed** [comment]
Fixed. The issue can be closed
