### ISSUE TITLE
'Processing ' service does not start properly

### ISSUE THREAD

**Issue by spiridonovfed** [epam/badgerdoc#45]
Logs from dev1:

Traceback (most recent call last):
  File "/usr/local/bin/alembic", line 5, in <module>
    from alembic.config import main
  File "/usr/local/lib/python3.8/site-packages/alembic/__init__.py", line 3, in <module>
    from . import context
  File "/usr/local/lib/python3.8/site-packages/alembic/context.py", line 1, in <module>
    from .runtime.environment import EnvironmentContext
  File "/usr/local/lib/python3.8/site-packages/alembic/runtime/environment.py", line 12, in <module>
    from .migration import MigrationContext
  File "/usr/local/lib/python3.8/site-packages/alembic/runtime/migration.py", line 17, in <module>
    from sqlalchemy import Column
ModuleNotFoundError: No module named 'sqlalchemy'

**Comment by thinklab** [comment]
Service redeployed, error not reproduced.
