### ISSUE TITLE
Incorrect work of the button "Edit" job

### ISSUE THREAD

**Issue by Iogsotot** [epam/badgerdoc#454]
**Step to reproduce:** 
1) go to **Extraction** tab
2) go to any **Job** page
3) click on **"Edit"** job button 

**Actual result:**
Page with navigation component, but without Edit job form
![image](https://user-images.githubusercontent.com/50149163/226627826-c10b515c-4d90-4961-baf8-6d97ebc61d8d.png)

**Expected result:** 
 Edit job form and job edit functionality
 
 *Network:
![image](https://user-images.githubusercontent.com/50149163/226628325-5fa8e356-298b-4026-925b-342db75abb34.png)
![image](https://user-images.githubusercontent.com/50149163/226628399-014b90c6-edb5-4986-b8e1-6469f57191a9.png)
![image](https://user-images.githubusercontent.com/50149163/226628488-1ec011c2-fc79-43eb-8b1c-c7ab90d41e55.png)

**Comment by Iogsotot** [comment]
Possible duplicate of https://github.com/epam/badgerdoc/issues/443

**Comment by serereg** [comment]
```
INFO:     10.233.96.227:49382 - "POST /api/v1/pipelines/pipelines/search HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/uvicorn/protocols/http/httptools_impl.py", line 375, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/usr/local/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.8/site-packages/fastapi/applications.py", line 208, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.8/site-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.8/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc
  File "/usr/local/lib/python3.8/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.8/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc
  File "/usr/local/lib/python3.8/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 656, in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 259, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 61, in app
    response = await func(request)
  File "/usr/local/lib/python3.8/site-packages/fastapi/routing.py", line 226, in app
    raw_response = await run_endpoint_function(
  File "/usr/local/lib/python3.8/site-packages/fastapi/routing.py", line 161, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "/usr/local/lib/python3.8/site-packages/starlette/concurrency.py", line 39, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
  File "/usr/local/lib/python3.8/site-packages/anyio-3.6.2-py3.8.egg/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/usr/local/lib/python3.8/site-packages/anyio-3.6.2-py3.8.egg/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/usr/local/lib/python3.8/site-packages/anyio-3.6.2-py3.8.egg/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/opt/pipelines/./pipelines/app.py", line 134, in search_pipelines
    query, pag = form_query(filter_args, query)
  File "/usr/local/lib/python3.8/site-packages/filter_lib-0.1.4-py3.8.egg/filter_lib/query_modificator.py", line 65, in form_query
    if sorting and not query._order_by:
AttributeError: 'Query' object has no attribute '_order_by'

```
