### ISSUE TITLE
Exception in annotation service: RecursionError: maximum recursion depth exceeded in comparison

### ISSUE THREAD

**Issue by khyurri** [epam/badgerdoc#495]
When user tries to run job with ~3000 files, he got 2 different exceptions

Job type: Manual annotation, Extensive coverage (possible others job types also affected)
Arguments: 1 owner, 1 validator, 4 annotators, every 

**Recursion exception**
```
30-Mar-23 14:29:38 - [ERROR] - annotation.logger - (main.py).catch_exceptions_middleware(77) - maximum recursion depth exceeded in comparison
Traceback (most recent call last):
  File "/opt/annotation/./annotation/main.py", line 75, in catch_exceptions_middleware
    return await call_next(request)
  File "/usr/local/lib/python3.8/site-packages/starlette/middleware/base.py", line 45, in call_next
    task.result()
  File "/usr/local/lib/python3.8/site-packages/starlette/middleware/base.py", line 38, in coro
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.8/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc from None
  File "/usr/local/lib/python3.8/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 580, in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 241, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 52, in app
    response = await func(request)
  File "/usr/local/lib/python3.8/site-packages/fastapi/routing.py", line 226, in app
    raw_response = await run_endpoint_function(
  File "/usr/local/lib/python3.8/site-packages/fastapi/routing.py", line 161, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "/usr/local/lib/python3.8/site-packages/starlette/concurrency.py", line 40, in run_in_threadpool
    return await loop.run_in_executor(None, func, *args)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/opt/annotation/./annotation/jobs/resources.py", line 192, in post_job
    distribute(
  File "/opt/annotation/./annotation/distribution/main.py", line 144, in distribute
    validation_tasks = distribute_tasks(
  File "/opt/annotation/./annotation/distribution/main.py", line 265, in distribute_tasks
    tasks = distribute_whole_files(  # type: ignore
  File "/opt/annotation/./annotation/distribution/main.py", line 407, in distribute_whole_files
    files_for_task = find_equal_files(
  File "/opt/annotation/./annotation/distribution/main.py", line 466, in find_equal_files
    find_pages_combination(files_pages, user_pages, pages_for_task)
  File "/opt/annotation/./annotation/distribution/main.py", line 489, in find_pages_combination
    find_pages_combination(
  File "/opt/annotation/./annotation/distribution/main.py", line 489, in find_pages_combination
    find_pages_combination(
  File "/opt/annotation/./annotation/distribution/main.py", line 489, in find_pages_combination
    find_pages_combination(
  [Previous line repeated 984 more times]
  File "/opt/annotation/./annotation/distribution/main.py", line 482, in find_pages_combination
    if combinations_sum == user_pages:
RecursionError: maximum recursion depth exceeded in comparison
``` 

**IndexError**
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/uvicorn/protocols/http/h11_impl.py", line 373, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/usr/local/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.8/site-packages/fastapi/applications.py", line 208, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.8/site-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.8/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc from None
  File "/usr/local/lib/python3.8/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.8/site-packages/starlette/middleware/base.py", line 25, in __call__
    response = await self.dispatch_func(request, self.call_next)
  File "/opt/annotation/./annotation/main.py", line 78, in catch_exceptions_middleware
    raise exception
  File "/opt/annotation/./annotation/main.py", line 75, in catch_exceptions_middleware
    return await call_next(request)
  File "/usr/local/lib/python3.8/site-packages/starlette/middleware/base.py", line 45, in call_next
    task.result()
  File "/usr/local/lib/python3.8/site-packages/starlette/middleware/base.py", line 38, in coro
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.8/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc from None
  File "/usr/local/lib/python3.8/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 580, in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 241, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 52, in app
    response = await func(request)
  File "/usr/local/lib/python3.8/site-packages/fastapi/routing.py", line 226, in app
    raw_response = await run_endpoint_function(
  File "/usr/local/lib/python3.8/site-packages/fastapi/routing.py", line 161, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "/usr/local/lib/python3.8/site-packages/starlette/concurrency.py", line 40, in run_in_threadpool
    return await loop.run_in_executor(None, func, *args)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/opt/annotation/./annotation/jobs/resources.py", line 192, in post_job
    distribute(
  File "/opt/annotation/./annotation/distribution/main.py", line 114, in distribute
    annotation_tasks = distribute_tasks_extensively(
  File "/opt/annotation/./annotation/distribution/main.py", line 196, in distribute_tasks_extensively
    if annotators[0]["pages_number"] >= MAX_PAGES:
```

**Comment by cakeinsauce** [comment]
@khyurri the fix is merged to main. Should we pass it to the QA?

**Comment by khyurri** [comment]
No, let's close it
