### ISSUE TITLE
Bug in release 1.1.0 on Vertex env - Internal Server Error in 'annotation' on 'categories/search'

### ISSUE THREAD

**Issue by spiridonovfed** [epam/badgerdoc#90]
Logs:
INFO:     100.120.37.66:32944 - "POST /api/v1/annotation/categories/search HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/uvicorn/protocols/http/h11_impl.py", line 373, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/usr/local/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.8/site-packages/fastapi/applications.py", line 208, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.8/site-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.8/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc from None
  File "/usr/local/lib/python3.8/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.8/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc from None
  File "/usr/local/lib/python3.8/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
.................................
  File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 241, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 52, in app
    response = await func(request)
  File "/usr/local/lib/python3.8/site-packages/fastapi/routing.py", line 226, in app
    raw_response = await run_endpoint_function(
  File "/usr/local/lib/python3.8/site-packages/fastapi/routing.py", line 161, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "/usr/local/lib/python3.8/site-packages/starlette/concurrency.py", line 40, in run_in_threadpool
    return await loop.run_in_executor(None, func, *args)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/opt/annotation/./app/categories/resources.py", line 134, in search_categories
    task_response = filter_category_db(db, request, x_current_tenant)
  File "/opt/annotation/./app/categories/services.py", line 350, in filter_category_db
    _get_parents(db, child_categories, tenant, job_id),
  File "/opt/annotation/./app/categories/services.py", line 281, in _get_parents
    uniq_pathes.add(cat.tree.path)
AttributeError: 'NoneType' object has no attribute 'path'

**Comment by MagicTearsAsunder** [comment]
fixed [here](https://github.com/epam/badgerdoc/pull/81/commits/d04f1e0182d537fbd9076fd23a8f47ea0e32b67d)

**Comment by MagicTearsAsunder** [comment]
fixed [here](https://github.com/epam/badgerdoc/pull/81/commits/d04f1e0182d537fbd9076fd23a8f47ea0e32b67d)
also fixed existing data on dev1 and vertex env
